[atom]
id = "world"
version = "0.1.0"
system = true

[fetch.mkAtom]
name = "make-atom"
type = "import"

[fetch.typed-atom]
name = "typed-atom"

[fetch.pkgs]
name = "nixpkgs"

[fetch.pkdjz]

[fetch.horizons-rs]

[fetch.liGoldragonWebpage]
type = "src"

[backend.nix]
fetcher = "flake-lock"