[atom]
id = "world"
version = "0.1.0"
system = true

[features]
default = [ "lib", "pkgs" ]

[fetch.mkAtom]
name = "make-atom"
type = "import"

[fetch.typed-atom]
name = "typed-atom"

[fetch.lib]
name = "lib"
type = "import"
subdir = "lib"

[fetch.pkgs]
name = "nixpkgs"
type = "pkgs"

[fetch.pkdjz]

[backend.nix]
fetcher = "flake-lock"